---
author: "Michael Karp"
title: "Getting and Cleaning Data - Quiz4 - Data Science Specialization"
date: 1/29/2015
output: 
html_document:
keep_md: true
---
  
```{r, echo = TRUE, results ='asis'}
# q1 - Load the cell segmentation data from the AppliedPredictiveModeling package using the commands:

```


```{r, dependson="createTree", fig.height=4.5, fig.width=4.5}
# q2 - If K is small in a K-fold cross validation is the bias in the estimate of out-of-sample (test set) accuracy
# smaller or bigger? If K is small is the variance in the estimate of out-of-sample (test set) accuracy smaller or
# bigger. Is K large or small in leave one out cross validation? The bias is larger and the variance is smaller. 
# Under leave one out cross validation K is equal to the sample size.
``` 

```{r, echo = TRUE, results ='asis'}
# q3 - Load the olive oil data using the commands:
````
```{r, echo = TRUE, results ='asis'}
# q4 - Load the South Africa Heart Disease Data and create training and test sets with the following code:
```
```{r, echo = TRUE, results ='asis'}
# q5 - You can use the quantmod (http://www.quantmod.com/) package to get historical stock prices for publicly traded companies on the NASDAQ and NYSE. Use the following code to download data on Amazon's stock price and get the times the data was sampled.
library(quantmod)
amzn = getSymbols("AMZN",auto.assign=FALSE)
sampleTimes = index(amzn) 
# How many values were collected in 2012? How many values were collected on Mondays in 2012?
table(as.Date(sampleTimes) >= as.Date("2012-01-01") & as.Date(sampleTimes) <= as.Date("2012-12-31"))
table(as.Date(sampleTimes) >= as.Date("2012-01-01") & as.Date(sampleTimes) <= as.Date("2012-12-31") & weekdays(as.Date(sampleTimes)) == "Monday")
```